### ISSUE TITLE
0.0.3 npm release does not have compiled output

### ISSUE THREAD

**Issue by gondalez** [sudsy/node-find-files#2]
Hi,

I noticed the package is missing the .js file, so I am seeing _Cannot find module_ error.

This is a diff between the packages 0.0.2 and 0.0.3.
![](http://puu.sh/gGwvd/10431576c5.png)

**Comment by jackcasey** [comment]
+1 This is affecting older versions (0.1.18) of jest-cli which pulled in the new version of this dependancy automatically.

**Comment by catalinmiron** [comment]
+1

**Comment by Sirlon** [comment]
+1

**Comment by catalinmiron** [comment]
In the meantime, you can use our fork: https://github.com/uberVU/jest which uses `node-find-files` v.0.0.2. What do you need to do is to add `"jest-cli": "git://github.com/ubervu/jest",` instead of `"jest-cli": "...."`

**Comment by kelseymok** [comment]
+1

**Comment by sudsy** [comment]
Compiled versions now in git and package for version 0.0.4
Sincere apologies

**Comment by gondalez** [comment]
Thanks for the quick fix :+1:
