### ISSUE TITLE
Error if no filterFunction option is added.

### ISSUE THREAD

**Issue by ruimarques** [sudsy/node-find-files#3]
If you call finder the following way, you get 'undefined is not a function' errors for every file match, because there is no default filterFunction and the code assumes such function was set in the options.

```
 var finder = new FindFiles({
        rootFolder: "/home"
 });
```

If, for example, the filterFunction is set like this, everything works fine: 

```
var finder = new FindFiles({
                rootFolder: "/home",
                filterFunction: function () {
                    return true;
                }
 });
```

**Comment by sudsy** [comment]
Fixed with 1.0.0 release
